spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:h2:mem:case;DB_CLOSE_DELAY=0;DB_CLOSE_ON_EXIT=TRUE;LOCK_MODE=0
      connection-test-query: SELECT 1
      pool-name: websocket-messaging
      username: websocket-user
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      format_sql: true
      ddl_auto: update
    open-in-view: true

  h2:
    console:
      enabled: false

  server:
    port: 8080